const SUPABASE_URL='https://uppdrbhtxgczpapfxgdk.supabase.co';
const SUPABASE_KEY='sb_publishable_H20OIk47Kleeja1iROnwFQ_sAz_vN4z';
const SCHEMA30_URL='https://raw.githubusercontent.com/schemaorg/schemaorg/v30.0/data/schema.ttl';
const VERIFIED_GIT_BLOB='e24bac4b0005848e7f4b7f0316276a449ddc08ce';
let session=JSON.parse(localStorage.getItem('power_ai_session')||'null'),profile=null,terms=[],termMap=new Map(),filter='all',expFilter='all',authMode='login',deferredPrompt=null,currentTerm='Person';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(window._tt);window._tt=setTimeout(()=>t.classList.add('hidden'),3800)}
function decodeLit(s){return String(s||'').replace(/\\n/g,'\n').replace(/\\"/g,'"').replace(/\\\\/g,'\\')}
function extractNames(s){return [...String(s||'').matchAll(/:([A-Za-z][\w-]*)/g)].map(m=>m[1])}
function parseTTL(text){
 const starts=[...text.matchAll(/^:([A-Za-z0-9_-]+)\s+a\s+([^;]+);/gm)],blocks=[];
 const grab=(body,key)=>{const i=body.indexOf(key);if(i<0)return[];let seg=body.slice(i+key.length),end=seg.length;const semi=seg.indexOf(';');if(semi>=0)end=Math.min(end,semi);const dot=seg.search(/\n\s*\.\s*(?:\n|$)/);if(dot>=0)end=Math.min(end,dot);return extractNames(seg.slice(0,end))};
 for(let i=0;i<starts.length;i++){
  const m=starts[i],name=m[1],type=m[2].trim(),start=m.index+m[0].length,end=i+1<starts.length?starts[i+1].index:text.length,body=text.slice(start,end);
  const kind=type.includes('rdf:Property')?'property':type.includes('rdfs:Class')?'class':'value';
  const lm=body.match(/rdfs:label\s+"((?:\\.|[^"\\])*)"/),cm3=body.match(/rdfs:comment\s+"""([\s\S]*?)"""/),cm=body.match(/rdfs:comment\s+"((?:\\.|[^"\\])*)"/);
  blocks.push({name,kind,label:decodeLit(lm?.[1]||name),comment:decodeLit(cm3?.[1]||cm?.[1]||''),parents:grab(body,'rdfs:subClassOf'),domains:grab(body,':domainIncludes'),ranges:grab(body,':rangeIncludes'),supers:grab(body,'rdfs:subPropertyOf'),inverse:grab(body,':inverseOf'),children:[]});
 }
 const map=new Map(blocks.map(x=>[x.name,x]));for(const t of blocks)for(const p of t.parents)if(map.has(p))map.get(p).children.push(t.name);return blocks
}
async function loadSchema(){try{$('#dataStat').textContent='Loading';const r=await fetch(SCHEMA30_URL,{cache:'force-cache'});if(!r.ok)throw new Error('Schema 30.0 '+r.status);const txt=await r.text();terms=parseTTL(txt);if(terms.length<1500)throw new Error('Schema parser returned only '+terms.length+' terms');termMap=new Map(terms.map(x=>[x.name,x]));const c=terms.filter(x=>x.kind==='class').length,p=terms.filter(x=>x.kind==='property').length,v=terms.filter(x=>x.kind==='value').length,rel=terms.reduce((n,x)=>n+x.parents.length+x.domains.length+x.ranges.length+x.inverse.length,0);$('#mClasses').textContent=c.toLocaleString();$('#mProps').textContent=p.toLocaleString();$('#mValues').textContent=v.toLocaleString();$('#mRels').textContent=rel.toLocaleString();$('#schemaStatus').textContent=`Exact Schema.org 30.0 loaded · ${terms.length.toLocaleString()} terms`;$('#dataStat').textContent='Verified';renderSearch('',false);renderExplorer('',false);renderPopular();renderDashGraph('Person')}catch(e){$('#dataStat').textContent='ERROR';$('#schemaStatus').textContent='Data load failed — no fake fallback used';toast(e.message)}}
function score(t,q){q=q.toLowerCase();if(!q)return 1;let s=0,n=t.name.toLowerCase(),l=t.label.toLowerCase(),c=t.comment.toLowerCase();if(n===q)s+=100;if(n.startsWith(q))s+=55;if(n.includes(q))s+=35;if(l.includes(q))s+=20;if(c.includes(q))s+=6;if([...t.parents,...t.domains,...t.ranges].some(x=>x.toLowerCase().includes(q)))s+=5;return s}
function searchTerms(q,f='all'){return terms.map(t=>[t,score(t,q)]).filter(([t,s])=>(!q||s>0)&&(f==='all'||t.kind===f)).sort((a,b)=>b[1]-a[1]||a[0].name.localeCompare(b[0].name)).map(x=>x[0])}
function resultHTML(t){return `<article class="result" data-term="${esc(t.name)}"><span class="tag">${esc(t.kind)}</span><h4>${esc(t.label)}</h4><p>${esc((t.comment||'Schema.org vocabulary term.').slice(0,150))}</p></article>`}
function renderSearch(q='',log=false){const out=searchTerms(q,filter);$('#searchCount').textContent=out.length.toLocaleString()+' results';$('#searchResults').innerHTML=out.slice(0,90).map(resultHTML).join('');if(log)logEvent('schema_search',{query:q,source:'global',result_count:out.length})}
function renderExplorer(q='',log=false){const out=searchTerms(q,expFilter);$('#explorerResults').innerHTML=out.slice(0,120).map(resultHTML).join('');if(log)logEvent('schema_search',{query:q,source:'explorer',result_count:out.length})}
function openTerm(name){const t=termMap.get(name);if(!t)return;currentTerm=name;switchView('explorer');$('#detailPanel').classList.remove('hidden');$('#detailTitle').textContent=t.label;$('#detailKind').textContent=t.kind+' · Schema.org 30.0';$('#detailComment').textContent=t.comment||'No description in source.';let groups=[['Parents',t.parents],['Children',t.children],['Domains',t.domains],['Ranges',t.ranges],['Inverse',t.inverse]];$('#detailRelations').innerHTML=groups.filter(x=>x[1].length).map(([k,a])=>`<div class="item"><div><b>${k}</b><span>${a.map(x=>esc(x)).join(', ')}</span></div></div>`).join('')||'<div class="item"><div><b>No direct relations listed</b></div></div>';$('#detailJson').textContent=JSON.stringify({'@context':'https://schema.org','@type':t.kind==='class'?t.name:'Thing',name:'Example'},null,2);logEvent('schema_open',{term:name,kind:t.kind})}
function renderPopular(){const names=['Person','Organization','Product','Event','Article','Place'];const cols=['#176dff','#25b5a2','#ff7343','#ef4a92','#3d96ff','#ee4ca4'];$('#popular').innerHTML=names.map((n,i)=>{const t=termMap.get(n);return t?`<div class="item" data-term="${n}"><div class="ico" style="background:${cols[i]}">${i+1}</div><div><b>${n}</b><span>${esc(t.comment.slice(0,75))}</span></div></div>`:''}).join('');$('#popularSearch').innerHTML=names.map(n=>`<div class="item" data-search="${n}"><div class="ico" style="background:#13558e">⌕</div><div><b>${n}</b><span>Search exact 30.0 vocabulary</span></div></div>`).join('')}
function switchView(v){$$('.view').forEach(x=>x.classList.remove('active'));$('#view-'+v)?.classList.add('active');$$('.sbtn').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));if(v==='analytics')loadAnalytics();if(v==='admin')loadAdmin();window.scrollTo({top:0,behavior:'smooth'})}
$$('.sbtn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-nav]').forEach(b=>b.onclick=()=>switchView(b.dataset.nav));document.addEventListener('click',e=>{const j=e.target.closest('[data-jump]');if(j)switchView(j.dataset.jump);const t=e.target.closest('[data-term]');if(t)openTerm(t.dataset.term);const s=e.target.closest('[data-search]');if(s){switchView('search');$('#globalQ').value=s.dataset.search;renderSearch(s.dataset.search,true)}const tool=e.target.closest('[data-tool]');if(tool){switchView('tools');openTool(tool.dataset.tool)}});
$('#heroSearch').onclick=()=>{switchView('search');$('#globalQ').value=$('#heroQ').value;renderSearch($('#heroQ').value,true)};$('#globalSearch').onclick=()=>renderSearch($('#globalQ').value,true);$('#explorerSearch').onclick=()=>renderExplorer($('#explorerQ').value,true);$$('[data-filter]').forEach(b=>b.onclick=()=>{$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderSearch($('#globalQ').value,false)});$$('[data-expfilter]').forEach(b=>b.onclick=()=>{$$('[data-expfilter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');expFilter=b.dataset.expfilter;renderExplorer($('#explorerQ').value,false)});$('#detailGraphBtn').onclick=()=>{switchView('graph');$('#graphQ').value=currentTerm;drawGraph(currentTerm)};
function relationSet(t){const a=[];if($('#gParents')?.checked)a.push(...t.parents.map(x=>[x,'class','parent']),...t.children.map(x=>[x,'class','child']));if($('#gProps')?.checked)for(const p of terms)if(p.kind==='property'&&(p.domains.includes(t.name)||p.ranges.includes(t.name)))a.push([p.name,'property',p.domains.includes(t.name)?'property':'range']);if($('#gRanges')?.checked)a.push(...t.domains.map(x=>[x,'class','domain']),...t.ranges.map(x=>[x,termMap.get(x)?.kind||'value','range']),...t.inverse.map(x=>[x,'property','inverse']));const seen=new Set();return a.filter(x=>x[0]!==t.name&&!seen.has(x[0])&&seen.add(x[0])).slice(0,18)}
function drawGraph(name){const t=termMap.get(name)||searchTerms(name)[0];if(!t){toast('Term not found');return}currentTerm=t.name;$('#graphQ').value=t.name;const rel=relationSet(t),wrap=$('#graphWrap'),nodes=$('#graphNodes'),svg=$('#graphSvg'),w=wrap.clientWidth||900,h=wrap.clientHeight||560,cx=w/2,cy=h/2;nodes.innerHTML='';svg.innerHTML='';const mk=(n,x,y,cls,center=false)=>{const d=document.createElement('button');d.className='gnode '+cls+(center?' center':'');d.textContent=n;d.style.left=x+'px';d.style.top=y+'px';d.onclick=()=>drawGraph(n);nodes.appendChild(d)};mk(t.name,cx,cy,t.kind,true);rel.forEach((r,i)=>{const ang=(Math.PI*2*i/Math.max(1,rel.length))-Math.PI/2,rad=Math.min(w,h)*(.32+(i%3)*.035),x=cx+Math.cos(ang)*rad,y=cy+Math.sin(ang)*rad*.82;const line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',cx);line.setAttribute('y1',cy);line.setAttribute('x2',x);line.setAttribute('y2',y);line.setAttribute('stroke','#315d86');line.setAttribute('stroke-width','1');svg.appendChild(line);mk(r[0],x,y,r[1])});$('#graphInfoTitle').textContent=t.label;$('#graphInfoText').textContent=t.comment||'No source description.';$('#graphInfoStats').textContent=`${rel.length} visible relations · ${t.parents.length} parents · ${t.children.length} children`;logEvent('graph_open',{term:t.name,visible_relations:rel.length})}
function renderDashGraph(name){const el=$('#dashGraph'),t=termMap.get(name);if(!t){el.innerHTML='<span class="muted">Loading graph…</span>';return}const r=relationSet(t).slice(0,6);el.innerHTML=`<div style="height:100%;position:relative">${r.map((x,i)=>{const pos=[[50,12],[78,28],[82,65],[50,82],[18,65],[18,28]][i];return `<button class="gnode ${x[1]}" data-dashgraph="${x[0]}" style="left:${pos[0]}%;top:${pos[1]}%">${esc(x[0])}</button>`}).join('')}<button class="gnode center" data-dashgraph="${name}" style="left:50%;top:49%">${name}</button></div>`;el.querySelectorAll('[data-dashgraph]').forEach(b=>b.onclick=()=>{switchView('graph');drawGraph(b.dataset.dashgraph)})}
['gParents','gProps','gRanges'].forEach(id=>$('#'+id).onchange=()=>drawGraph(currentTerm));$('#graphGo').onclick=()=>drawGraph($('#graphQ').value.trim());
